const initialState = {
    books: [
      {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        img_url:"https://tse1.mm.bing.net/th?id=OIP.eTO09xqdGYiKU913AIb0vQHaJt&pid=Api&P=0&h=220",
        category: "Fiction",
        description: "A novel set in the 1920s about the American dream.",
        rating: 4.2,
      },
      {
        id: 2,
        title: "Sapiens: A Brief History of Humankind",
        author: "Yuval Noah Harari",
        img_url:"https://tse4.mm.bing.net/th?id=OIP.AZzsxY7oQbCqWItZXYsl7gHaKQ&pid=Api&P=0&h=220",
        category: "Non-Fiction",
        description: "An exploration of the history of humankind from the Stone Age to the modern day.",
        rating: 4.8,
      },
      {
        id: 3,
        title: "Dune",
        author: "Frank Herbert",
        img_url:"https://tse2.mm.bing.net/th?id=OIP.vzI4nma84IJGvKV3v-T2WAHaLL&pid=Api&P=0&h=220",
        category: "Sci-Fi",
        description: "A science fiction epic set in a desert world.",
        rating: 4.7,
      },
      // Adding more books
      {
        id: 4,
        title: "1984",
        author: "George Orwell",
        img_url:"https://tse2.mm.bing.net/th?id=OIP.L9GCrCznPuEmHSIHTIltkQHaLZ&pid=Api&P=0&h=220",
        category: "Fiction",
        description: "A dystopian novel set in a totalitarian society.",
        rating: 4.5,
      },
      {
        id: 5,
        title: "The Selfish Gene",
        author: "Richard Dawkins",
        img_url:"https://tse2.mm.bing.net/th?id=OIP.ZxQ64Evf--wVqAzIfFoiqgHaLR&pid=Api&P=0&h=220",
        category: "Non-Fiction",
        description: "An exploration of evolutionary biology from a gene-centered view.",
        rating: 4.3,
      },
      {
        id: 6,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        img_url:"https://tse4.mm.bing.net/th?id=OIP.p_i90gDsUej5GCJMagH7FQHaKj&pid=Api&P=0&h=220",
        category: "Fantasy",
        description: "The classic fantasy novel that introduces the world of Middle-Earth.",
        rating: 4.9,
      },
      {
        id: 7,
        title: "Neuromancer",
        author: "William Gibson",
        img_url:"https://tse3.mm.bing.net/th?id=OIP.dLRlHYoBf8-T7_ZeDCaRjgHaLH&pid=Api&P=0&h=220",
        category: "Sci-Fi",
        description: "A cyberpunk novel that explores artificial intelligence and cyberspace.",
        rating: 4.6,
      },
      {
        id: 8,
        title: "Educated",
        author: "Tara Westover",
        img_url:"https://tse3.mm.bing.net/th?id=OIP.lNPamzUfEdxQo7riJrgneQHaLv&pid=Api&P=0&h=220",
        category: "Non-Fiction",
        description: "A memoir about growing up in a strict, survivalist family and later achieving a formal education.",
        rating: 4.7,
      },
    ],
  };
  export default initialState;